# vim:set expandtab shiftwidth=4 filetype=toml:
# SPDX-License-Identifier: GPL-3.0-only
#:schema https://mise.jdx.dev/schema/mise.json

#
#
# ~chewygumxx/claude-sysprompt.git
# ::: :/mise.toml
#
#

[tools]
bun = "1.4"
