# vim:set expandtab shiftwidth=4 filetype=yaml foldlevel=3:
# SPDX-License-Identifier: GPL-3.0-only

#
#
# ~chewygumxx/claude-sysprompt.git
# ::: :/.github/workflows/ci.yaml
#
#

name: CI

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch: {}

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  node-version: 24
                  cache: npm

            - name: NPM Clean Install
              run: npm ci

            - name: Typecheck
              run: npm run typecheck

            - name: Build
              run: npm run build

            - name: Check Formatting
              run: npm run format:check

            - name: Lint Markdown
              run: npm run lint:md

            - name: Test
              run: npm test
